# Generated by Django 5.1.4 on 2026-08-30 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('trains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(db_index=True, max_length=10, unique=True)),
                ('journey_date', models.DateField(db_index=True)),
                ('class_type', models.CharField(db_index=True, max_length=20)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('RAC', 'RAC'), ('WAITING', 'Waiting'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='CONFIRMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriving_bookings', to='stations.station')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departing_bookings', to='stations.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='trains.train')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('id_type', models.CharField(max_length=40)),
                ('id_number', models.CharField(max_length=80)),
                ('seat_preference', models.CharField(blank=True, max_length=40)),
                ('meal_preference', models.CharField(blank=True, max_length=40)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to='bookings.booking')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='trains.coach')),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservation', to='bookings.passenger')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='trains.seat')),
            ],
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'journey_date'], name='bookings_bo_user_id_0de7b9_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['train', 'journey_date'], name='bookings_bo_train_i_09e53b_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['coach', 'journey_date'], name='bookings_se_coach_i_b26f0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='seatreservation',
            constraint=models.UniqueConstraint(fields=('seat', 'journey_date'), name='unique_seat_per_journey_date'),
        ),
    ]
