# Generated by Django 5.1.4 on 2026-08-30 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=20, unique=True)),
                ('train_name', models.CharField(max_length=140)),
                ('train_type', models.CharField(db_index=True, max_length=60)),
                ('running_days', models.JSONField(default=list)),
                ('distance', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance')], db_index=True, default='ACTIVE', max_length=20)),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_trains', to='stations.station')),
                ('source_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_trains', to='stations.station')),
            ],
            options={
                'ordering': ['train_number'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('halt_minutes', models.PositiveIntegerField(default=0)),
                ('distance_from_source', models.PositiveIntegerField(default=0)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='stations.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='trains.train')),
            ],
            options={
                'ordering': ['train', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(max_length=20)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservation_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='trains.train')),
            ],
            options={
                'ordering': ['train', 'class_type'],
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_number', models.CharField(max_length=12)),
                ('coach_type', models.CharField(db_index=True, max_length=40)),
                ('class_type', models.CharField(db_index=True, max_length=20)),
                ('total_seats', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='trains.train')),
            ],
            options={
                'ordering': ['train', 'coach_number'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('seat_type', models.CharField(default='Window', max_length=40)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('BLOCKED', 'Blocked')], db_index=True, default='AVAILABLE', max_length=20)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='trains.coach')),
            ],
            options={
                'ordering': ['coach', 'seat_number'],
                'constraints': [models.UniqueConstraint(fields=('coach', 'seat_number'), name='unique_coach_seat')],
            },
        ),
        migrations.AddIndex(
            model_name='train',
            index=models.Index(fields=['train_type', 'status'], name='trains_trai_train_t_f92f9e_idx'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('train', 'sequence'), name='unique_train_route_sequence'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('train', 'station'), name='unique_train_route_station'),
        ),
        migrations.AddConstraint(
            model_name='fare',
            constraint=models.UniqueConstraint(fields=('train', 'class_type'), name='unique_train_class_fare'),
        ),
        migrations.AddConstraint(
            model_name='coach',
            constraint=models.UniqueConstraint(fields=('train', 'coach_number'), name='unique_train_coach'),
        ),
    ]
